# Generated by Django 3.1.2 on 2020-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='overview',
            field=models.TextField(default=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
