# Generated by Django 3.1.2 on 2020-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0002_auto_20201023_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='overview',
            field=models.TextField(max_length=500),
        ),
    ]
