# Generated by Django 3.1.2 on 2020-10-28 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0004_auto_20201028_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movies',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
