# Generated by Django 3.1.2 on 2020-10-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0006_auto_20201029_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movies',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
    ]
