# Generated by Django 3.1.2 on 2020-10-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0007_auto_20201030_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movies',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
