# Generated by Django 3.1.3 on 2020-11-08 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0014_auto_20201108_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
