# Generated by Django 3.1.3 on 2020-11-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0018_auto_20201109_1656'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='duplicate'),
        ),
    ]
