# Generated by Django 3.1.3 on 2020-11-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0019_auto_20201111_1715'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='duplicate',
        ),
    ]
