# Generated by Django 3.1.3 on 2020-11-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0021_auto_20201111_1809'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='duplicate',
        ),
    ]
