# Generated by Django 3.1.3 on 2020-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0022_auto_20201111_1810'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='duplicate'),
        ),
    ]
