# Generated by Django 3.1.3 on 2020-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0023_auto_20201111_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
