# Generated by Django 3.1.3 on 2020-11-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0024_movie_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
        migrations.AddField(
            model_name='movie',
            name='taggs',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
