# Generated by Django 3.1.3 on 2020-11-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0025_auto_20201127_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='taggs',
            new_name='tag1',
        ),
        migrations.AddField(
            model_name='movie',
            name='tag10',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag3',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag4',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag5',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag6',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag7',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag8',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag9',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
