# Generated by Django 3.1.3 on 2020-11-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0028_auto_20201127_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag10',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag6',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag7',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag8',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag9',
        ),
        migrations.AddField(
            model_name='movie',
            name='taggs',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
