# Generated by Django 3.1.3 on 2020-11-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0030_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
