# Generated by Django 3.1.3 on 2020-11-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0031_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='taggs',
        ),
    ]
