# Generated by Django 3.1.3 on 2020-11-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0034_auto_20201127_1809'),
        ('moviedjango', '0024_movie_taggs'),
    ]

    operations = [
    ]
