# Generated by Django 3.1.3 on 2020-11-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0036_remove_movie_taggs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='tag',
            name='movies',
            field=models.ManyToManyField(to='moviedjango.Movie'),
        ),
    ]
