# Generated by Django 3.1.3 on 2020-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0037_auto_20201129_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='moviedjango.Tag'),
        ),
    ]
