# Generated by Django 3.1.3 on 2020-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0038_auto_20201130_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='movies',
            field=models.ManyToManyField(to='moviedjango.Movie'),
        ),
    ]
