# Generated by Django 3.1.3 on 2020-12-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0039_auto_20201130_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
