# Generated by Django 3.1.3 on 2020-12-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0040_movie_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
    ]
