# Generated by Django 3.1.3 on 2020-12-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0042_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
