# Generated by Django 3.1.3 on 2020-12-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0043_delete_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
